### ISSUE TITLE
Website demonstration doesn't work with latest Oculus Browser

### ISSUE THREAD

**Issue by mz8i** [stewdio/handy.js#3]
The demonstration at https://stewartsmith.io/handy/ doesn't work on Oculus Quest (v1), latest Oculus Browser (v14). The cosmic background shows up, but nothing else (hands or other UI).

An error occurs inside Three.js init code:
```
WebGL context must be marked as XR compatible in order to use with an immersive XRSession
three.module.js:23581
```

See here: https://github.com/mrdoob/three.js/issues/21126 - it seems to be a recent problem, presumably on all Chromium-based browsers, and should be fixed by updating to latest Three.

**Comment by stewdio** [comment]
Thank you for spotting this, and apologies for taking so long to respond. (Life, eh?)
While the issue you’ve raised is now resolved, a new one with a similar result has opened:
https://github.com/stewdio/handy.js/issues/4
